// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenRestoApi.Infrastructure.Persistence;

#nullable disable

namespace OpenRestoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728211946_HardenBookingOccasionSnapshotUniqueness")]
    partial class HardenBookingOccasionSnapshotUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PvqAnswerHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PvqAnswerSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PvqQuestion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminCredentials");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminCredentialManagementAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActorAdminCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorEmailSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialKeyIdSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperatorAgentCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeRestaurantIdsSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetOperatorIdentifierSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetOperatorPrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TtlHoursSnapshot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorAdminCredentialId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OperatorAgentCredentialId", "CreatedAtUtc");

                    b.HasIndex("TargetOperatorPrincipalId", "CreatedAtUtc");

                    b.ToTable("AdminCredentialManagementAudits");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PushError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PushSentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RestaurantId", "CreatedAt");

                    b.HasIndex("RestaurantId", "IsRead");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Endpoint", "RestaurantId")
                        .IsUnique();

                    b.ToTable("AdminPushSubscriptions");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByOperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedViaChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhoneE164")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhoneNormalized")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("SectionId");

                    b.HasIndex("TableId");

                    b.HasIndex("CreatedByOperatorId", "RestaurantId", "Date");

                    b.HasIndex("CustomerPhoneNormalized", "RestaurantId", "Date");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.BookingOccasionSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPriceCop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantOccasionCatalogItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingId", "RestaurantOccasionCatalogItemId")
                        .IsUnique();

                    b.ToTable("BookingOccasionSnapshots");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.BrandSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyrightText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaviconIcon")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderImageFit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsHeading")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsSubheading")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BrandSettings");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.ChannelMutationIdempotencyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Channel", "MutationScope", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ChannelMutationIdempotencyRecords");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.EmailFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailFailures");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendBookingConfirmations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorActionAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperatorAgentCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OperatorPrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorPrincipalIdSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestaurantIdSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorAgentCredentialId");

                    b.HasIndex("BookingId", "CreatedAt");

                    b.HasIndex("OperatorPrincipalId", "CreatedAt");

                    b.HasIndex("RestaurantId", "CreatedAt");

                    b.ToTable("OperatorActionAudits");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorAgentCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialKeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorPrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialKeyId")
                        .IsUnique();

                    b.HasIndex("OperatorPrincipalId");

                    b.HasIndex("ExpiresAt", "RevokedAt");

                    b.ToTable("OperatorAgentCredentials");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorPrincipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedIdentifier")
                        .IsUnique();

                    b.ToTable("OperatorPrincipals");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorRestaurantScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorPrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("OperatorPrincipalId", "RestaurantId")
                        .IsUnique();

                    b.ToTable("OperatorRestaurantScopes");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("BookingSlotIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BookingsPausedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultBookingDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTableOversizeSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenHoursJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WalkInDays")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WalkInOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.RestaurantHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.RestaurantOccasionCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPriceCop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "SortOrder");

                    b.ToTable("RestaurantOccasionCatalogItems");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SocialLinks");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminCredentialManagementAudit", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.AdminCredential", "ActorAdminCredential")
                        .WithMany()
                        .HasForeignKey("ActorAdminCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.OperatorAgentCredential", "OperatorAgentCredential")
                        .WithMany()
                        .HasForeignKey("OperatorAgentCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.OperatorPrincipal", "TargetOperatorPrincipal")
                        .WithMany()
                        .HasForeignKey("TargetOperatorPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorAdminCredential");

                    b.Navigation("OperatorAgentCredential");

                    b.Navigation("TargetOperatorPrincipal");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminNotification", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.AdminPushSubscription", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Booking", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.OperatorPrincipal", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenRestoApi.Core.Domain.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Restaurant");

                    b.Navigation("Section");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.BookingOccasionSnapshot", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorActionAudit", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.OperatorAgentCredential", "OperatorAgentCredential")
                        .WithMany()
                        .HasForeignKey("OperatorAgentCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.OperatorPrincipal", "OperatorPrincipal")
                        .WithMany()
                        .HasForeignKey("OperatorPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("OperatorAgentCredential");

                    b.Navigation("OperatorPrincipal");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorAgentCredential", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.OperatorPrincipal", "OperatorPrincipal")
                        .WithMany("Credentials")
                        .HasForeignKey("OperatorPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorPrincipal");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorRestaurantScope", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.OperatorPrincipal", "OperatorPrincipal")
                        .WithMany("RestaurantScopes")
                        .HasForeignKey("OperatorPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorPrincipal");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.RestaurantOccasionCatalogItem", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Section", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Restaurant", "Restaurant")
                        .WithMany("Sections")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Table", b =>
                {
                    b.HasOne("OpenRestoApi.Core.Domain.Section", "Section")
                        .WithMany("Tables")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.OperatorPrincipal", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("RestaurantScopes");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Restaurant", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("OpenRestoApi.Core.Domain.Section", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
