http:
  routers:
    test-rest-secure:
      rule: "Host(`test-rest.joypaw.tech`)"
      entryPoints:
        - websecure
      service: test-rest-openresto
      tls:
        certResolver: letsencrypt

    n8n-test-secure:
      rule: "Host(`n8n-test.joypaw.tech`)"
      entryPoints:
        - websecure
      service: n8n-test-service
      tls:
        certResolver: letsencrypt

  services:
    test-rest-openresto:
      loadBalancer:
        servers:
          - url: "http://test-rest-reverse-proxy:80"

    n8n-test-service:
      loadBalancer:
        servers:
          - url: "http://n8n-test:5678"
